# Generated by Django 5.1.2 on 2024-11-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convite',
            name='estado',
        ),
        migrations.AddField(
            model_name='convite',
            name='convite_type',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENVIADO', 'Enviado')], default='PENDENTE', max_length=10),
        ),
    ]
