# Generated by Django 5.1.2 on 2024-11-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_app', '0002_remove_convite_estado_convite_convite_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convite',
            name='convite_type',
            field=models.CharField(choices=[('------', '------'), ('PENDENTE', 'Pendente'), ('ENVIADO', 'Enviado')], default='------', max_length=10),
        ),
    ]
