# Generated by Django 5.1.2 on 2024-11-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_app', '0003_alter_convite_convite_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convite',
            name='convite_type',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENVIADO', 'Enviado')], default='PENDENTE', max_length=10),
        ),
    ]
