# Generated by Django 5.1.2 on 2024-11-08 14:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_app', '0006_alter_convite_limiteconvites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convite',
            name='limiteConvites',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
