# Generated by Django 5.1.2 on 2024-11-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0002_remove_feedback_produtoid_remove_feedback_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='dataHoraEnvio',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(choices=[('----------', '----------'), ('RECLAME', 'Reclamação'), ('SUGESTA', 'Sugestão'), ('ELOGIO', 'Elogio')], default='----------', max_length=10),
        ),
    ]
