# Generated by Django 5.1.2 on 2024-11-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('autenticado', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='content',
            old_name='description',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='title',
            new_name='titulo',
        ),
        migrations.RemoveField(
            model_name='content',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='content',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='content',
            name='file_url',
        ),
        migrations.RemoveField(
            model_name='content',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='content',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='content',
            name='status',
        ),
        migrations.RemoveField(
            model_name='content',
            name='thumbnail_url',
        ),
        migrations.RemoveField(
            model_name='content',
            name='upload_date',
        ),
        migrations.RemoveField(
            model_name='content',
            name='views',
        ),
    ]
